# Generated by Django 3.2.6 on 2021-11-27 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cameras',
            fields=[
                ('camera_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('camera_name', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('latitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Cameras',
            },
        ),
        migrations.CreateModel(
            name='Functions',
            fields=[
                ('function_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('function_name', models.CharField(max_length=200)),
                ('function_type', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Functions',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('groups_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('job_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=200)),
                ('recurrence', models.CharField(max_length=200)),
                ('from_date', models.DateField(verbose_name='from date')),
                ('to_date', models.DateField(blank=True, null=True, verbose_name='to date')),
                ('start_time', models.TimeField()),
                ('sme_alert', models.BooleanField(blank=True, null=True)),
                ('email_alert', models.BooleanField(blank=True, null=True)),
                ('status', models.CharField(default='INQUEUE', max_length=50)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnalyticsPlatformApi.functions')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnalyticsPlatformApi.groups')),
            ],
            options={
                'db_table': 'Jobs',
            },
        ),
        migrations.CreateModel(
            name='log',
            fields=[
                ('detectionid', models.IntegerField(primary_key=True, serialize=False)),
                ('functiontype', models.CharField(max_length=200)),
                ('objectid', models.IntegerField()),
                ('filename', models.CharField(max_length=200)),
                ('framecount', models.IntegerField()),
                ('totalframes', models.IntegerField()),
                ('classid', models.BigIntegerField()),
                ('classname', models.CharField(max_length=200)),
                ('coordinates', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(verbose_name='timestamp')),
                ('jobid', models.BigIntegerField(default=1)),
                ('sourceid', models.BigIntegerField(default=1)),
                ('sub_sourceid', models.BigIntegerField(default=1)),
                ('sub_sourcename', models.CharField(default='vid', max_length=200)),
                ('retscore', models.IntegerField(default=50)),
                ('model_label_id', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'log',
            },
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('model_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=200)),
                ('architecture', models.CharField(max_length=200)),
                ('label_file_path', models.TextField(blank=True, null=True)),
                ('model_file_path', models.TextField(blank=True, null=True)),
                ('model_specname', models.TextField(blank=True, default='obj_detection', null=True)),
                ('model_signature', models.TextField(blank=True, default='serving_default', null=True)),
                ('comments', models.TextField(blank=True, default='comments', null=True)),
            ],
            options={
                'db_table': 'Models',
            },
        ),
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('operation_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('operation_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Operations',
            },
        ),
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('source_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('source_name', models.CharField(max_length=200)),
                ('source_type', models.CharField(max_length=200)),
                ('cameras', models.TextField(blank=True, null=True)),
                ('sub_sources', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Sources',
            },
        ),
        migrations.CreateModel(
            name='streaming_url',
            fields=[
                ('jobid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('sub_source_id', models.BigIntegerField()),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='Running', max_length=50)),
            ],
            options={
                'db_table': 'streaming_url',
            },
        ),
        migrations.CreateModel(
            name='sub_sources',
            fields=[
                ('sub_source_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('sub_source_name', models.CharField(max_length=200)),
                ('folder_path', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sub_sources',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('tasks_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='processed_video',
            fields=[
                ('processed_video_id', models.IntegerField(primary_key=True, serialize=False)),
                ('video_file_name', models.CharField(max_length=200)),
                ('processed_date', models.DateTimeField(verbose_name='timestamp')),
                ('path', models.TextField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnalyticsPlatformApi.jobs')),
                ('source_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnalyticsPlatformApi.sources')),
                ('sub_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnalyticsPlatformApi.sub_sources')),
            ],
            options={
                'db_table': 'processed_video',
            },
        ),
        migrations.CreateModel(
            name='Model_labels',
            fields=[
                ('label_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('model_label_id', models.BigIntegerField(default=1)),
                ('label_name', models.CharField(max_length=200)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnalyticsPlatformApi.models')),
            ],
            options={
                'db_table': 'Model_labels',
            },
        ),
        migrations.AddField(
            model_name='jobs',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnalyticsPlatformApi.sources'),
        ),
        migrations.CreateModel(
            name='Function_parameters',
            fields=[
                ('param_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('param_name', models.CharField(max_length=200)),
                ('param_type', models.CharField(max_length=20)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnalyticsPlatformApi.functions')),
            ],
            options={
                'db_table': 'Function_parameters',
            },
        ),
        migrations.CreateModel(
            name='Function_lto',
            fields=[
                ('lto_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnalyticsPlatformApi.functions')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnalyticsPlatformApi.model_labels')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnalyticsPlatformApi.operations')),
            ],
            options={
                'db_table': 'Function_lto',
            },
        ),
    ]
