# Generated by Django 3.2.6 on 2021-11-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnalyticsPlatformApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processed_video',
            name='processed_date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
