# Generated by Django 3.2.6 on 2022-10-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnalyticsPlatformApi', '0003_alter_processed_video_source_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelsDevelop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1200, verbose_name='Model Name')),
                ('description', models.TextField(verbose_name='Model Description')),
            ],
        ),
        migrations.RemoveField(
            model_name='cameras',
            name='camera_id',
        ),
        migrations.AddField(
            model_name='cameras',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cameras',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='cameras',
            name='url',
            field=models.CharField(blank=True, max_length=1200),
        ),
        migrations.AlterModelTable(
            name='cameras',
            table=None,
        ),
    ]
