apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-claim0
spec:
  capacity:
   storage: 10Gi
  accessModes:
   - ReadWriteOnce
   - ReadOnlyMany
   - ReadWriteMany
  hostPath:
    path: "/mnt/app-claim0"
  claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: app-claim0
      namespace: default