apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 1
  template:
    metadata:
      annotations:
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/main: "true"
        io.kompose.service: app
    spec:
      containers:
        - args:
            - sh
            - -c
            - wait-for &&  python3 app/manage.py migrate && python3 app/manage.py runserver 0.0.0.0:8000
          env:
            - name: ALLOWED_HOSTS
              value: "*"
            - name: WAIT_HOSTS
              value: postgres:5432
            - name: WAIT_HOSTS_TIMEOUT
              value: "50"
            - name: WAIT_HOST_CONNECT_TIMEOUT
              value: "30"
            - name: WAIT_SLEEP_INTERVAL
              value: "30"
          image: app-image:latest
          imagePullPolicy: Never
          name: app
          securityContext:
            capabilities:
              add: ["NET_ADMIN", "SYS_ADMIN"]
            runAsUser: 0

          ports:
            - containerPort: 8000
          resources: {}
          volumeMounts:
            # - mountPath: /usr/src/app
            #   name: app-claim0
            - mountPath: /usr/src/vizsense_volume
              name: viz-data
      hostname: app
      restartPolicy: Always
      volumes:
        # - name: app-claim0
        #   persistentVolumeClaim:
        #     claimName: app-claim0
        - name: viz-data
          persistentVolumeClaim:
            claimName: viz-data
status: {}
