apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: k8s-rabbitmq-data
  name: k8s-rabbitmq-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: edge-ic4
  resources:
    requests:
      storage: 100Mi
status: {}
