apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-data
spec:
  capacity:
   storage: 10Gi
  accessModes:
   - ReadWriteOnce
  hostPath:
    path: "/mnt/postgresql-data"
  claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: postgresql-data
      namespace: default
