apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/main: "true"
        io.kompose.service: postgres
    spec:
      containers:
        - env:
            - name: WAIT_HOSTS
              value: postgres:5432
            - name: POSTGRES_DB
              value: apexroot1
            - name: POSTGRES_PASSWORD
              value: apexroot1
            - name: POSTGRES_USER
              value: apexroot1
          image: postgres:latest
          name: postgres
          #imagePullPolicy: Never
          ports:
            - containerPort: 5432
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresql-data
      hostname: postgres
      restartPolicy: Always
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: postgresql-data
status: {}
