apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: default
  name: rabbitmq-data
spec:
  capacity:
   storage: 10Gi
  accessModes:
   - ReadWriteMany
  storageClassName: edge-ic4
  hostPath:
    path: "/mnt/k8s-rabbitmq-data/"
  claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: k8s-rabbitmq-data
      namespace: default
