apiVersion: v1
kind: PersistentVolume
metadata:
  name: viz-data
spec:
  capacity:
   storage: 10Gi
  accessModes:
   - ReadWriteOnce
   - ReadOnlyMany
   - ReadWriteMany
  hostPath:
    path: "/mnt/viz-data"
  claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: viz-data
      namespace: default
