apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: worker
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/main: "true"
        io.kompose.service: worker
    spec:
      containers:
        - args:
            - sh
            - -c
            - python3 Worker/worker.py
          image: app-image:latest
          imagePullPolicy: Never
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
          name: worker
          resources: 
            limits:
                    # aliyun.com/gpu-mem: 1
              nvidia.com/gpu: 0
          volumeMounts:
            # - mountPath: /usr/src/app
            #   name: app-claim0
            - mountPath: /usr/src/vizsense_volume
              name: viz-data
      volumes:
        # - name: app-claim0
        #   persistentVolumeClaim:
        #     claimName: app-claim0
        - name: viz-data
          persistentVolumeClaim:
            claimName: viz-data
      tolerations:
        - effect: NoSchedule
          operator: Exists
          
      hostname: worker
      restartPolicy: Always

status: {}
